# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='user_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='blog_text',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='document',
            name='blog_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
